### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by rikvdkleij** [tensorflow/haskell#175]
Thanks for developing this project!

What is the status of this project? Is it production ready? Also, for some time there has been no release anymore and TF itself is by now on version 1.5. As far as I can see is currently TF version 1.3 supported. I assume the C API of TF changes with each version.

**Comment by blackgnezdo** [comment]
Rik, I do not know of anybody using this code in production. Since this is an open source project people are free to do as they please and never tell us. Upgrading to TF 1.5 should not be a huge undertaking based on our prior upgrades (e.g. #161). If it isn't entirely trivial, maybe one would have to blacklist a few ops that happen to require the features we don't support.

**Comment by rikvdkleij** [comment]
@blackgnezdo Thanks for your explanation!
