### ISSUE TITLE
Architecture of this project?

### ISSUE THREAD

**Issue by doofin** [tensorflow/haskell#198]
Sorry if this is the wrong place to ask,but I can not find an IRC or gitter  room.

I am trying to build an idris version (https://github.com/doofin/tensorflow-idris) , but I can't understand how the graph construction operators are generated (https://github.com/tensorflow/haskell/blob/1e2dca870125a2941359f14f5e02971a28d6e199/tensorflow-ops/src/TensorFlow/Ops.hs). I would also like to know more about the structure of this project,thanks!

**Comment by blackgnezdo** [comment]
@doofin, first thing you should realize is TF APIs we rely on exchange protocol buffers. If you have a PB library for Idris, you can start by generating the values for TF PBs. Once you have serialized PBs into bytes, those need to be sent across to the language boundary to the TF C++ library. We leverage Haskell FFI for this.

Now, when we started this was the only way to interface with TF runtime. Since then the preferred API changed and instead of funnelling complicated PB data structures there is a large C library that can be wrapped instead. I haven't looked at it closely in over a year.

**Comment by doofin** [comment]
Thanks! I am working on to port the c api  of tf now

**Comment by blackgnezdo** [comment]
I'm closing the issue, please feel free to ask again if you need help.
