### ISSUE TITLE
Help with gradient function for pad

### ISSUE THREAD

**Issue by rikvdkleij** [tensorflow/haskell#225]
We need some help in implementing the `opGrad` function for the `pad` function.

Assuming `x` and `padpattern` are the input to the pad function:
```
pad input padpattern
```
Our understanding is that the gradient should look like:
```
opGrad "Pad" _ [toT -> x] [dz] = [Just $ slice dz padgradpattern (shape x)]
```

where `padgradpattern` is the first column of the `padpattern`.

The question is how to get the `padgradpattern` in the `opGrad` function?

**Comment by fkm3** [comment]
Ignoring the first argument, the signature looks like

```haskell
type GradientFunc a = NodeDef
                    -> [Output]
                    -- ^ Input tensors.
                    -> [Tensor Value a]
                    -- ^ Gradient of y w.r.t. each output tensor.
                    -> [Maybe (Tensor Build a)]
                    -- ^ Gradient of y w.r.t. each input tensor.
```

The third parameter contains an `Output` for each input. If you use `[toT -> x]`, you are expecting exactly one input (and converting it from `Output` to `Tensor Build a`). Since `pad` has two inputs, you probably want `[toT -> x, toT -> padpattern]`.

---

Sorry if the gradient code is confusing. I think it should be possible to rewrite it such that it is type safe and clear, but I haven't had the energy to do it yet.

**Comment by rikvdkleij** [comment]
@fkm3 Thanks! That was really helpful information. We continue with the implementation.
