### ISSUE TITLE
Using a UI framework with TensorFlow bindings

### ISSUE THREAD

**Issue by mohanr** [tensorflow/haskell#67]
Are there some instructions to use TensorFlow and stream the result to Yesod ? Is Docker needed for this type of setup ?

**Comment by fkm3** [comment]
Docker isn't needed, it is just the easiest way to deal with the tensorflow dependencies ATM. If Docker is getting in the way, you can try to follow the OS X install instructions (but follow https://bazel.build/versions/master/docs/install.html instead of using `brew install bazel`, use .so instead of .dylib, etc).

I haven't used yesod before, so I can't comment on it, but there should be nothing special required to use tensorflow with a UI library. When you run a tensorflow computation, the result is usually a multidimensional array. How you use that array to generate HTML is completely dependent on your use case.

**Comment by mohanr** [comment]
install bazel-bin/tensorflow/libtensorflow_c.so /usr/local/lib/libtensorflow_c.dylib
     install_name_tool -id libtensorflow_c.dylib /usr/local/lib/libtensorflow_c.dylib

It built. These 2 lines should change ?

**Comment by fkm3** [comment]
There will be a binary release of tensorflow soon (not sure how soon exactly), which will make the install instructions much simpler. I'll probably add instructions for that once it is available. In the interim, if you'd like add the steps you took, feel free to send a PR. I'm sure someone would find it useful.
